#!/usr/bin/bash
# sdk/deb/lib/package.sh — Ubuntu kernel Debian packaging (from source).
#
# Produces Ubuntu kernel .deb packages from the kernel source tree using the
# tree's own debian/rules machinery (dpkg-buildpackage) — the cranky-correct
# native Ubuntu packaging. debian/rules owns the kernel configuration and
# version machinery; we inject the board's kconfig via Ubuntu annotations.
#
# Qualcomm-specific steps folded in (see DESIGN.md § Divergences):
#   - mrproper: the native packaging builds out-of-tree and refuses a dirty tree
#   - drop the zfs-linux DKMS (only arm64 DKMS here; not part of the image)
#   - annotate: merge the snapd + customer kconfig fragments via annotations
#   - updateconfigs: reconcile the cross / no-rust environment

[[ -n "${_DEB_PACKAGE_SH:-}" ]] && return 0
_DEB_PACKAGE_SH=1

# deb_install_build_deps ROOT ARCH — apt-get build-dep against the tree.
# NOTE: must be called AFTER `debian/rules clean`, because Ubuntu kernel trees
# generate debian/control from debian/control.stub during clean; the file does
# not exist in a fresh clone.
deb_install_build_deps() {
    local root="${1}" arch="${2}"
    local src="${root}/kernel-src"
    if [[ "${SKIP_BUILD_DEPS:-0}" == "1" ]]; then
        workshop_log "Skipping build-dep install (SKIP_BUILD_DEPS=1)."
        return 0
    fi
    [[ -f "${src}/debian/control" ]] || {
        workshop_warn "debian/control not present yet; skipping build-dep (generated by clean)."
        return 0
    }
    workshop_log "Installing kernel build-deps (apt-get build-dep, arch: ${arch})..."
    ( cd "${src}"
      sudo apt-get update -qq
      sudo DEBIAN_FRONTEND=noninteractive apt-get build-dep -y -a "${arch}" . ) >&2 \
        || workshop_warn "build-dep install incomplete (common under cross: perf/tools deps clash on python3:${arch}). Continuing — the kernel image/modules/headers do not need them; the build-host provisioning (noble-build/setup-base) already installs the core deps."
    return 0
}

# deb_annotate ROOT — inject the configured kconfig fragments into the tree's
# Ubuntu annotations the Canonical way (`annotations --update`), recording the
# customer delta as flavour overrides (snapd options are inherited from the
# Canonical base). Must run in-tree (annotations use a relative include).
deb_annotate() {
    local root="${1}"
    local src="${root}/kernel-src"
    cd "${src}"

    [[ -f debian/debian.env ]] || workshop_fail "kernel-src is not an Ubuntu-packaged tree (no debian/debian.env)"
    local deb flav ann
    deb="$(sed -n 's/^DEBIAN=//p' debian/debian.env)"           # e.g. debian.rubikpi
    flav="${CFG_KERNEL_CONFIG_VALUE}"
    ann="${deb}/config/annotations"
    [[ -n "${flav}" ]] || workshop_fail "kernel.config.value (flavour) is empty"

    # Assemble the merged fragment: snapd/customer (from config) + any
    # kernel.config.disable symbols rendered as "is not set".
    local merged="/tmp/${CFG_SILICON_BOARD}-bsp.config"
    : > "${merged}"
    local IFS='|' f
    for f in ${CFG_KERNEL_CONFIG_FRAGMENTS:-}; do
        [[ -n "${f}" ]] || continue
        local abs="${root}/${f}"
        [[ -f "${abs}" ]] || workshop_fail "kconfig fragment not found: ${abs}"
        cat "${abs}" >> "${merged}"
        echo >> "${merged}"
    done
    unset IFS
    local sym
    for sym in ${CFG_KERNEL_DISABLE_CONFIGS//|/ }; do
        [[ -n "${sym}" ]] || continue
        echo "# CONFIG_${sym} is not set" >> "${merged}"
    done

    if [[ ! -s "${merged}" ]]; then
        workshop_log "No kconfig fragments/disables configured; skipping annotate."
        return 0
    fi

    workshop_log "annotations --update ${ann} (arch arm64, flavour ${flav}) from config fragments ..."
    python3 debian/scripts/misc/annotations -f "${ann}" -a arm64 -l "${flav}" --update "${merged}" \
        || workshop_fail "annotations --update failed"
    return 0
}

# deb_build ROOT ARCH — builds binary .debs into the source parent dir.
deb_build() {
    local root="${1}" arch="${2}"
    local src="${root}/kernel-src"

    [[ -d "${src}" ]] || workshop_fail "Kernel source not found at kernel-src"
    [[ -f "${src}/debian/rules" ]] || workshop_fail "${src}/debian/rules not found — not an Ubuntu kernel packaging tree?"

    # A prior root build (snapcraft --destructive-mode) may leave root-owned
    # files that break debian/rules clean. Reset ownership unless disabled.
    if [[ "${SKIP_CHOWN:-0}" != "1" ]] \
       && [[ -n "$(find "${src}" -maxdepth 1 ! -user "$(id -u)" -print -quit 2>/dev/null)" ]]; then
        workshop_log "Resetting ownership of kernel-src (left by a root build); SKIP_CHOWN=1 to skip."
        sudo chown -R "$(id -u):$(id -g)" "${src}"
    fi

    local cross
    case "${arch}" in
        arm64) cross="aarch64-linux-gnu-" ;;
        armhf) cross="arm-linux-gnueabihf-" ;;
        amd64) cross="" ;;
        *) workshop_fail "Unsupported arch '${arch}' (arm64|armhf|amd64)" ;;
    esac
    [[ -n "${CROSS_COMPILE:-}" ]] && cross="${CROSS_COMPILE}"

    (
        cd "${src}"
        export ARCH="${arch}"
        export CROSS_COMPILE="${cross}"
        # Cap parallelism (a full -j$(nproc) kernel build saturates CPU+RAM).
        export DEB_BUILD_OPTIONS="parallel=$(workshop_jobs) ${DEB_BUILD_OPTIONS:-}"

        if [[ "${SKIP_CLEAN:-0}" != "1" ]]; then
            # Native packaging builds out-of-tree (O=debian/build/...) and refuses
            # a dirty source tree; a prior in-tree build leaves a stale .config +
            # objects, so start pristine (config comes from annotations, not .config).
            workshop_log "Cleaning tree pristine (mrproper + debian/rules clean); SKIP_CLEAN=1 to skip..."
            make ARCH="${arch}" mrproper >&2 || workshop_warn "mrproper reported issues; continuing"
            fakeroot debian/rules clean >&2 || workshop_fail "debian/rules clean failed"
        fi

        # Build-deps must be installed AFTER clean (clean generates debian/control
        # on Ubuntu kernel trees). Native/host arch handled via the -a<arch> flag.
        deb_install_build_deps "${root}" "${arch}"

        # Drop the zfs DKMS: only arm64 DKMS here, needs the dkms tool + zfs
        # build-deps, and is not part of the kernel image.
        local deb; deb="$(sed -n 's/^DEBIAN=//p' debian/debian.env)"
        sed -i '/^zfs-linux /d' "${deb}"/dkms-versions 2>/dev/null || true

        # Inject the board kconfig (customer delta + snapd) into the annotations,
        # then reconcile the env-driven options (cross, no-rust) via updateconfigs.
        deb_annotate "${root}"
        fakeroot debian/rules updateconfigs >&2 || workshop_warn "updateconfigs reported issues; continuing"

        workshop_log "Building kernel .debs from source for ${arch} (cross: '${cross}')..."
        dpkg-buildpackage -a"${arch}" -B -d -uc -us \
            ${BUILDPACKAGE_OPTS:-} \
            >&2 || workshop_fail "dpkg-buildpackage failed"
    )
    return 0
}

# deb_stage ROOT — collect produced .debs into out/deb/.
deb_stage() {
    local root="${1}"
    local parent="${root}"   # dpkg-buildpackage writes to the source tree's parent (project root)
    local out="${root}/out/deb"

    mkdir -p "${out}/metadata"
    rm -rf "${out:?}"/* 2>/dev/null || true
    mkdir -p "${out}/metadata"

    local count=0 f
    shopt -s nullglob
    for f in "${parent}"/*.deb; do
        mv -f "${f}" "${out}/"
        count=$((count+1))
    done
    for f in "${parent}"/*.changes "${parent}"/*.buildinfo; do
        mv -f "${f}" "${out}/metadata/" 2>/dev/null || true
    done
    shopt -u nullglob

    [[ "${count}" -gt 0 ]] || workshop_fail "No .deb files were produced."
    workshop_log "Staged ${count} .deb(s) → out/deb/"
    ( cd "${out}" && ls -1 *.deb ) > "${out}/metadata/packages.txt"
    return 0
}
