#!/usr/bin/bash
# sdk/deb/lib/package.sh — Ubuntu kernel Debian packaging (from source).
#
# Produces Ubuntu kernel .deb packages from the kernel source tree using the
# tree's own debian/rules machinery (dpkg-buildpackage). This is the proper
# Ubuntu/Debian kernel packaging mechanism; debian/rules owns the kernel
# configuration and version machinery.

[[ -n "${_DEB_PACKAGE_SH:-}" ]] && return 0
_DEB_PACKAGE_SH=1

# deb_install_build_deps ROOT ARCH — apt-get build-dep against the tree.
# NOTE: must be called AFTER `debian/rules clean`, because Ubuntu kernel trees
# (e.g. linux-renesas) generate debian/control from debian/control.stub during
# clean; the file does not exist in a fresh clone.
deb_install_build_deps() {
    local root="${1}" arch="${2}"
    local src="${root}/kernel-src"
    if [[ "${SKIP_BUILD_DEPS:-0}" == "1" ]]; then
        workshop_log "Skipping build-dep install (SKIP_BUILD_DEPS=1)."
        return 0
    fi
    [[ -f "${src}/debian/control" ]] || {
        workshop_warn "debian/control not present yet; skipping build-dep (will be generated by clean)."
        return 0
    }
    workshop_log "Installing kernel build-deps (apt-get build-dep, arch: ${arch})..."
    ( cd "${src}"
      sudo apt-get update -qq
      sudo DEBIAN_FRONTEND=noninteractive apt-get build-dep -y -a "${arch}" . ) >&2 \
        || workshop_warn "build-dep install incomplete (common for cross builds; the perf/tools deps clash on python3:${arch}). Continuing — kernel image/modules/headers do not need them; linux-tools/perf are skipped via do_tools=false."
    return 0
}

# deb_build ROOT ARCH — builds binary .debs into the source parent dir.
deb_build() {
    local root="${1}" arch="${2}"
    local src="${root}/kernel-src"

    [[ -d "${src}" ]] || workshop_fail "Kernel source not found at kernel-src"
    [[ -f "${src}/debian/rules" ]] || workshop_fail "${src}/debian/rules not found — not an Ubuntu kernel packaging tree?"

    # A prior root build (snapcraft --destructive-mode) may leave root-owned
    # files that break `debian/rules clean`. Reset ownership unless disabled.
    if [[ "${SKIP_CHOWN:-0}" != "1" ]] \
       && [[ -n "$(find "${src}" -maxdepth 1 ! -user "$(id -u)" -print -quit 2>/dev/null)" ]]; then
        workshop_log "Resetting ownership of kernel-src (left by a root build); SKIP_CHOWN=1 to skip."
        sudo chown -R "$(id -u):$(id -g)" "${src}"
    fi

    local cross
    case "${arch}" in
        arm64) cross="aarch64-linux-gnu-" ;;
        armhf) cross="arm-linux-gnueabihf-" ;;
        amd64) cross="" ;;
        *) workshop_fail "Unsupported arch '${arch}' (arm64|armhf|amd64)" ;;
    esac
    [[ -n "${CROSS_COMPILE:-}" ]] && cross="${CROSS_COMPILE}"

    workshop_register_binfmt "${arch}"

    (
        cd "${src}"
        export ARCH="${arch}"
        export CROSS_COMPILE="${cross}"
        # dpkg-architecture -a<arch> also exports CC=<arch>-gcc etc.
        export $(dpkg-architecture -a"${arch}")

        if [[ "${SKIP_CLEAN:-0}" != "1" ]]; then
            workshop_log "Cleaning tree (SKIP_CLEAN=1 to skip)..."
            fakeroot debian/rules clean >&2 || workshop_fail "debian/rules clean failed"
        fi

        # Build-deps must be installed AFTER clean (clean generates
        # debian/control on Ubuntu kernel trees). Native/host arch handled by
        # apt via the -a<arch> flag inside deb_install_build_deps.
        deb_install_build_deps "${root}" "${arch}"

        workshop_log "Building kernel .debs from source for ${arch} (cross: '${cross}')..."
        # do_tools=false: skip linux-tools/perf/cloud-tools sub-packages. These
        # are runtime profiling/diagnostic tools (perf, cpupower, bpftool), not
        # needed by the kernel image/modules, and their build-deps (clang/llvm/
        # rust/python3-dev) are what clash under cross (-a<arch>) resolution.
        # Ubuntu kernel debian/rules reads these as make/env variables (?=).
        export do_tools=false
        export do_doc_package=false
        dpkg-buildpackage -b -uc -us -a"${arch}" -d \
            ${BUILDPACKAGE_OPTS:-} \
            >&2 || workshop_fail "dpkg-buildpackage failed"
    )
    return 0
}

# deb_stage ROOT — collect produced .debs into out/deb/.
deb_stage() {
    local root="${1}"
    local parent="${root}"   # dpkg-buildpackage writes to the source tree's parent (project root)
    local out="${root}/out/deb"

    # out/deb is a normal project dir; clear its contents for a fresh stage.
    mkdir -p "${out}/metadata"
    rm -rf "${out:?}"/* 2>/dev/null || true
    mkdir -p "${out}/metadata"

    local count=0 f
    shopt -s nullglob
    for f in "${parent}"/*.deb; do
        mv -f "${f}" "${out}/"
        count=$((count+1))
    done
    for f in "${parent}"/*.changes "${parent}"/*.buildinfo; do
        mv -f "${f}" "${out}/metadata/" 2>/dev/null || true
    done
    shopt -u nullglob

    [[ "${count}" -gt 0 ]] || workshop_fail "No .deb files were produced."
    workshop_log "Staged ${count} .deb(s) → out/deb/"
    ( cd "${out}" && ls -1 *.deb ) > "${out}/metadata/packages.txt"
    return 0
}
